export const fieldConfigData = [{
    level: 1,
    name: '订单视频信息',
    field: 'orderVideoInfo',
    children: [{
      level: 2,
      name: '平台订单信息',
      cancel: false,
      defaultShow: 1,
      exportDefaultShow: 1,
      aggregation: true,
      width: '350px',
      align: 'left',
      field: 'platOrderInfo',
      type: 'accountInfo',
      children: [{
        level: 3,
        name: '账号id',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'accountId'
      }, {
        level: 3,
        name: '账号名称',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'accountName'
      }, {
        level: 3,
        name: '平台',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'platName'
      }, {
        level: 3,
        name: '平台订单ID',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'platOrderId'
      }, {
        level: 3,
        name: '平台任务名称',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'platOrderName'
      }, {
        level: 3,
        name: '平台任务创建时间',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'platCreatetime'
      }]
    }, {
      level: 2,
      name: '视频信息',
      cancel: false,
      defaultShow: 1,
      exportDefaultShow: 1,
      aggregation: true,
      width: '405px',
      align: 'left',
      field: 'videoInfo',
      type: 'video',
      exportNotCancel: true,
      children: [{
        level: 3,
        name: '视频id',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'videoId'
      }, {
        level: 3,
        name: '视频标题',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'videoTitle'
      }, {
        level: 3,
        name: '视频链接',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'videoUrl'
      }, {
        level: 3,
        name: '视频发布时间',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'videoCreateTime'
      }, {
        level: 3,
        name: '视频状态',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'isDeleted'
      }, {
        level: 3,
        name: '组件类型',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'linkUseType'
      }, {
        level: 3,
        name: '组件渠道号',
        cancel: false,
        defaultShow: 1,
        exportDefaultShow: 1,
        field: 'androidDeliveryName'
      }]
    }]
  }, {
    level: 1,
    name: '人员信息',
    field: 'personInfo',
    children: [{
      level: 2,
      name: '人员信息',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      aggregation: true,
      width: '300px',
      align: 'left',
      field: 'persionInfoS',
      type: 'personInfo',
      children: [{
          level: 3,
          name: '军',
          field: 'dname',
          cancel: true,
          defaultShow: 1,
          exportDefaultShow: 1
        }, {
          level: 3,
          name: '团',
          field: 'fname',
          cancel: true,
          defaultShow: 1,
          exportDefaultShow: 1
        },
        {
          level: 3,
          name: '编辑人员',
          field: 'editUserName',
          cancel: true,
          defaultShow: 1,
          exportDefaultShow: 1
        },
        {
          level: 3,
          name: '剪辑人员',
          field: 'cutUserName',
          cancel: true,
          defaultShow: 1,
          exportDefaultShow: 1
        },
        {
          level: 3,
          name: '网红',
          field: 'influencer',
          cancel: true,
          defaultShow: 1,
          exportDefaultShow: 1
        }
      ]
    }]
  }, {
    level: 1,
    name: '标签信息',
    field: 'tagInfo',
    children: [{
      level: 2,
      name: '视频标签',
      field: 'videoTag',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1
    }, {
      level: 2,
      name: '内容类别',
      field: 'contentType',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1
    }, {
      level: 2,
      name: '产品型号',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      aggregation: true,
      field: 'productModel',
      format: '-',
      children: [{
        level: 3,
        name: '产品品类',
        field: 'coCateName',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '产品品牌',
        field: 'brandName',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '产品型号',
        field: 'b2cPhoneModel',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }]
    }, {
      level: 2,
      name: '视频类型',
      field: 'junType',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1
    }]
  }, {
    level: 1,
    name: '投放信息',
    field: 'putInfo',
    children: [{
      level: 2,
      name: '平台消耗金额',
      field: 'consumeAmount',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: '投放金额',
      field: 'deliveryMoney',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      isNumber: true,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: '返款金额',
      field: 'rebateAmount',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }]
  }, {
    level: 1,
    name: '投放基础效果指标',
    field: 'putBaseInfo',
    children: [{
        level: 2,
        name: '播放量',
        field: 'flowCount',
        type: 'flowCount',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        width: '200px'
      }, {
        level: 2,
        name: '7天播放量',
        field: 'nealy7dAddFlow',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: '即视频发布后7天的播放量（不含视频发布时间当日，不足7天按实际播放量展示）'
      }, {
        level: 2,
        name: '14天播放量',
        field: 'nealy14dAddFlow',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: '即视频发布后14天的播放量（不含视频发布时间当日，不足14天按实际播放量展示）'
      }, {
        level: 2,
        name: '点赞量',
        field: 'thumbUpCount',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      }, {
        level: 2,
        name: '评论量',
        field: 'commentCount',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      }, {
        level: 2,
        name: '转发量',
        field: 'forwardedCount',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      }, {
        level: 2,
        name: '组件点击量',
        field: 'cptClick',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      },
      // {
      //   level: 2,
      //   name: '新增激活',
      //   field: 'activeUV',
      //   cancel: true,
      //   defaultShow: 1,
      // exportDefaultShow: 1,
      //   summary: true,
      //   sort: true,
      //   tip: '以曝光口径为准'
      // }, {
      //   level: 2,
      //   name: '组件点击新增激活',
      //   field: 'newActiveUv',
      //   cancel: true,
      //   defaultShow: 1,
      // exportDefaultShow: 1,
      //   summary: true,
      //   sort: true
      // },
      {
        level: 2,
        name: 'CPM',
        field: 'cpm',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        isNumber: true,
        summary: true,
        sort: true,
        tip: 'CPM=投放金额/（流量/1000)'
      }, {
        level: 2,
        name: 'CPA',
        field: 'cpa',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: 'CPA=投放金额/总新增，即拉新用户的广告成本'
      }, {
        level: 2,
        name: '新增促活成本',
        field: 'newActivationCosts',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: '新增促活成本 = 投放金额/（总新增+总促活）'
      },
      {
        level: 2,
        name: '总新增',
        field: 'allNewReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: '包含曝光和组件点击，对新用户的拉新量'
      },
      {
        level: 2,
        name: '总促活',
        field: 'allRecallReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true,
        tip: '包含曝光和组件点击，对老用户的召回量'
      },
      {
        level: 2,
        name: '曝光新增',
        field: 'showNewReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      },
      {
        level: 2,
        name: '曝光促活',
        field: 'showRecallReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      },
      {
        level: 2,
        name: '组件点击新增',
        field: 'clickNewReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      },
      {
        level: 2,
        name: '组件点击促活',
        field: 'clickRecallReachUv',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1,
        summary: true,
        sort: true
      }
    ]
  },
  {
    level: 1,
    name: 'B2C',
    field: 'b2c',
    children: [{
      level: 2,
      name: 'B2C订单客单价',
      field: 'b2cOrderCustomerUnitPrice',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C总GMV/B2C总成交量'
    }, {
      level: 2,
      name: 'B2C-GPM',
      field: 'b2cGPM',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: '千次播放的GMV,B2C总GMV/播放量*1000'
    }, {
      level: 2,
      name: 'B2C总净支付数量',
      field: 'b2cAllNetPayOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'B2C手机净支付数量',
      field: 'b2cPhoneNetPayOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'B2C新3C净支付数量',
      field: 'b2cNew3cNetPayOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'B2C多品类净支付数量',
      field: 'b2cExt3cNetPayOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'B2C总GMV',
      field: 'b2cTotalGmv',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: '手机净支付金额+多品类净支付金额'
    }, {
      level: 2,
      name: 'B2C3天总GMV',
      field: 'b2cTotalGmvFront3Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后3天的总GMV'
    }, {
      level: 2,
      name: 'B2C7天总GMV',
      field: 'b2cTotalGmvFront7Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后7天的总GMV'
    }, {
      level: 2,
      name: 'B2C14天总GMV',
      field: 'b2cTotalGmvFront14Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后14天的总GMV'
    }, {
      level: 2,
      name: 'B2C手机GMV',
      field: 'b2cPhoneGmv',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C手机净支付金额'
    }, {
      level: 2,
      name: 'B2C新3CGMV',
      field: 'b2cNew3cNetPayAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C新3C总成交金额'
    }, {
      level: 2,
      name: 'B2C多品类GMV',
      field: 'b2cMultiCategoryGmv',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C多品类总成交金额'
    }, {
      level: 2,
      name: 'B2C总GMV-ROI',
      field: 'b2cTotalGmvRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C总GMV/投放价格'
    }, {
      level: 2,
      name: 'B2C手机GMV-ROI',
      field: 'b2cPhoneGmvRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C手机净支付金额/投放价格'
    }, {
      level: 2,
      name: 'B2C新3CGMV-ROI',
      field: 'b2cNew3cNetPayAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C新3C净支付金额/投放价格'
    }, {
      level: 2,
      name: 'B2C多品类GMV-ROI',
      field: 'b2cMultiCategoryGmvRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C多品类交易额/投放价格'
    }, {
      level: 2,
      name: 'B2C总利润',
      field: 'b2cTotalProfit',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C手机利润+B2C多品类利润'
    }, {
      level: 2,
      name: 'B2C手机利润',
      field: 'b2cPhoneProfit',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C手机净支付GMV*5%'
    }, {
      level: 2,
      name: 'B2C新3C利润',
      field: 'b2cNew3cNetPayAmtProfit',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C新3C净支付GMV*5%'
    }, {
      level: 2,
      name: 'B2C多品类利润',
      field: 'b2cMultiCategoryProfit',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C多品类净支付GMV*5%'
    }, {
      level: 2,
      name: 'B2C总利润ROI',
      field: 'b2cTotalProfitRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C总利润/投放价格'
    }, {
      level: 2,
      name: 'B2C手机利润ROI',
      field: 'b2cPhoneProfitRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C手机利润/投放价格'
    }, {
      level: 2,
      name: 'B2C新3C利润ROI',
      field: 'b2cNew3cNetPayAmtProfitRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C新3C利润/投放价格'
    }, {
      level: 2,
      name: 'B2C多品类利润ROI',
      field: 'b2cMultiCategoryProfitRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'B2C多品类利润/投放价格'
    }]
  }, {
    level: 1,
    name: 'C2B',
    field: 'c2b',
    children: [{
      level: 2,
      name: 'C2B回收客单价',
      field: 'c2bOrderCustomerUnitPrice',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B总GMV/C2B总成交量'
    }, {
      level: 2,
      name: 'C2B-GPM',
      field: 'c2bGPM',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: '千次播放的GMV，C2B总GMV/播放量*1000'
    }, {
      level: 2,
      name: 'C2B总回收数',
      field: 'c2bTotalRecovery',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B上门总回收数',
      field: 'recSmhsFinishOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B邮寄总回收数',
      field: 'recC2bFinishOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B手机回收数',
      field: 'c2bPhoneTotalRecovery',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B笔记本回收数',
      field: 'recBookReceiveOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B平板回收数',
      field: 'recPadReceiveOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B新3C回收数',
      field: 'recNew3cReceiveOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B多品类回收数',
      field: 'recExt3cReceiveOrderQty',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B总GMV',
      field: 'c2bTotalGmv',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B手机回收净支付金额+C2B电脑平板GMV'
    }, {
      level: 2,
      name: 'C2B上门总GMV',
      field: 'recSmhsFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B邮寄总GMV',
      field: 'recC2bFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B3天总GMV',
      field: 'c2bTotalGmvFront3Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后3天的总GMV'
    }, {
      level: 2,
      name: 'C2B7天总GMV',
      field: 'c2bTotalGmvFront7Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后7天的总GMV'
    }, {
      level: 2,
      name: 'C2B14天总GMV',
      field: 'c2bTotalGmvFront14Day',
      cancel: true,
      defaultShow: 0,
      exportDefaultShow: 0,
      summary: true,
      sort: true,
      tip: '视频发布后14天的总GMV'
    }, {
      level: 2,
      name: 'C2B手机GMV',
      field: 'c2bPhoneGmv',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B手机回收净支付金额'
    }, {
      level: 2,
      name: 'C2B笔记本GMV',
      field: 'recBookFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B平板GMV',
      field: 'recPadFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B新3CGMV',
      field: 'recNew3cFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B多品类GMV',
      field: 'recExt3cFinishOrderAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B总GMV-ROI',
      field: 'c2bTotalGmvRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B总GMV/投放价格'
    }, {
      level: 2,
      name: 'C2B上门总GMV-ROI',
      field: 'recSmhsFinishOrderAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B邮寄总GMV-ROI',
      field: 'recC2bFinishOrderAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B手机GMV-ROI',
      field: 'c2bPhoneGmvRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B手机回收GMV/投放价格'
    }, {
      level: 2,
      name: 'C2B新3CGMV-ROI',
      field: 'recNew3cFinishOrderAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B多品类GMV-ROI',
      field: 'recExt3cFinishOrderAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B总预估利润',
      field: 'c2bRecAllPredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: '每条视频对应得每个订单价格区间，按照相应的算法算利润'
    }, {
      level: 2,
      name: 'C2B上门总预估利润',
      field: 'recSmhsPredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B邮寄总预估利润',
      field: 'recC2bPredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B手机预估利润',
      field: 'c2bRecPhonePredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B新3C预估利润',
      field: 'recNew3cPredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B多品类预估利润',
      field: 'recExt3cPredictProfitAmt',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B总预估利润ROI',
      field: 'c2bRecAllPredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B总预估利润/投放价格'
    }, {
      level: 2,
      name: 'C2B上门总预估利润ROI',
      field: 'recSmhsPredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B邮寄总预估利润ROI',
      field: 'recC2bPredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B手机预估利润ROI',
      field: 'c2bRecPhonePredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true,
      tip: 'C2B手机预估利润/投放价格'
    }, {
      level: 2,
      name: 'C2B新3C预估利润ROI',
      field: 'recNew3cPredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B多品类预估利润ROI',
      field: 'recExt3cPredictProfitAmtRoi',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      summary: true,
      sort: true
    }, {
      level: 2,
      name: 'C2B回收价格区间',
      cancel: true,
      defaultShow: 1,
      exportDefaultShow: 1,
      aggregation: true,
      width: '340px',
      align: 'left',
      field: 'c2bPriceSection',
      type: 'c2bPriceSection',
      children: [{
        level: 3,
        name: '【0~100元）回收量',
        field: 'recAllFinish0100OrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '【100~400元）回收量',
        field: 'recAllFinish100400OrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '【400~900元）回收量',
        field: 'recAllFinish400900OrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '【900~1800元）回收量',
        field: 'recAllFinish9001800OrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '【1800~3000元）回收量',
        field: 'recAllFinish18003000OrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }, {
        level: 3,
        name: '【3000元及以上】回收量',
        field: 'recAllFinish3000InfOrderQty',
        cancel: true,
        defaultShow: 1,
        exportDefaultShow: 1
      }]
    }]
  }
]

export const fieldSortConfigData = fieldConfigData.map(item => {
  return item.children.map(it => {
    // delete it.children

    if (it.defaultShow) {
      return it
    } else {
      return ''
    }
  }).filter(it => it)
}).flat(Infinity)
